### ISSUE TITLE
Support & style all post formats

### ISSUE THREAD

**Issue by valendesigns** [valendesigns/archetype#5]
#### Functionality
- [x] OptionTree Integration #24
- [x] Link title is writing over all titles #54
- [x] Add first Gallery image to the post navigation #55
- [x] Clean up bxSlider Sass #56
- [x] Add single permalink to gallery link in archive #57
#### Styles
- [x] aside
- [x] gallery
- [x] link
- [x] image
- [x] quote
- [x] status
- [x] video
- [x] audio
- [x] chat
